package com.lrj.benefit.contract;

public enum BenefitErrorCode {
    INVALID_INTENT,
    IDEMPOTENCY_PAYLOAD_CONFLICT,
    SKU_NOT_FOUND,
    INVENTORY_INSUFFICIENT,
    CHANNEL_RETRYABLE,
    CHANNEL_FINAL_FAILURE,
    CHANNEL_RESULT_UNKNOWN,
    REMEDIATION_NOT_ALLOWED,
    INTERNAL_ERROR
}
