package com.lrj.benefit.contract;

public enum BenefitErrorCode {
    INVALID_INTENT,
    IDEMPOTENCY_PAYLOAD_CONFLICT,
    SKU_NOT_FOUND,
    SKU_NOT_ACTIVE,
    SKU_NOT_DRAFT,
    SKU_VERSION_CONFLICT,
    SKU_APPROVAL_LOCKED,
    SKU_ILLEGAL_TRANSITION,
    SKU_SUBMIT_IN_FLIGHT,
    SKU_APPROVAL_NOT_PENDING,
    APPROVAL_RUNTIME_UNAVAILABLE,
    WALLET_ENTRY_NOT_FOUND,
    WALLET_ILLEGAL_TRANSITION,
    WALLET_ALREADY_USED,
    WALLET_VERSION_CONFLICT,
    WALLET_EXPIRED,
    USER_LIMIT_EXCEEDED,
    INVENTORY_INSUFFICIENT,
    CHANNEL_RETRYABLE,
    CHANNEL_FINAL_FAILURE,
    CHANNEL_RESULT_UNKNOWN,
    REMEDIATION_NOT_ALLOWED,
    INTERNAL_ERROR
}
